### ISSUE TITLE
Unable to extend site lifetime

### ISSUE THREAD

**Issue by jblz** [oskosk/jurassic.ninja#98]
The notice in the dashboard says my site:
> will be destroyed 7 days after the last time anybody logged in.

I've found that the site goes away after some timeout regardless of how often I'm using it.

---

I tried to hit the [`extend` endpoint](https://github.com/oskosk/jurassic.ninja/blob/5e96fa678c406197cf93e00d7b75d2446b4c7b2d/lib/rest-api-stuff.php#L139), but haven't had success:

`curl 'https://jurassic.ninja/wp-json/jurassic.ninja/extend' --data 'domain=empty-elephant'`
...gives: 
`{"code":"no_domain_in_body","message":"You must pass a valid \"domain\" prop in the body","data":null}`

Am I doing it wrong? How can I keep a test site around for a while? Thanks!

**Comment by oskosk** [comment]
Just logout and login again. it also helps to activate Jetpack, SSO and login that way. everytime your session expires and you SSO in, the site gets extended.

**Comment by oskosk** [comment]
Maybe you were expecting that the lifespan would be extended just by visiting wp-admin ?

**Comment by jblz** [comment]
I figured out what I was doing wrong w/ the REST API `/extend` call...

`curl --data` implies `-x POST`, but I needed to tell it I was sending JSON..

This works:

```curl 'https://jurassic.ninja/wp-json/jurassic.ninja/extend' --data '{ "domain": "empty-elephant.jurassic.ninja" }' --header 'content-type: application/json'
{"status":"ok","data":{"url":"empty-elephant.jurassic.ninja"}}
```

> Maybe you were expecting that the lifespan would be extended just by visiting wp-admin ?

Ya -- something like that.  Maybe a hook into `admin_init` would be cool :slightly_smiling_face:

In any case, I'll go ahead and close this. Thanks for the reply!
